### PR TITLE
Update component versions

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Add tekton-pipeline release `v0.21.0`

Add tetkton-triggers release `v0.11.2`

Add tekton-dashboard release `v0.14.0`

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by savitaashture — APPROVED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
