### PR TITLE
add support to pipelines controller's performance flags

### PR DESCRIPTION
**Pull request by jkandasa**
# Changes

With this PR, Operator introduces new properties to update/change pipelines controller's HA support and performance configurations

new fields structured as follows in `TektonConfig` CR
```
spec:
  pipeline:
    ...fields omitted ...
    performance:
      disable-ha: false
      buckets: 3
      threads-per-controller: 3
      kube-api-qps: 40
      kube-api-burst: 40
```
NOTE: replicas count not handled by `TecktonConfig` CR. replicas should be applied manually by user with the following command,
```
kubectl --namespace tekton-pipelines scale deployment tekton-pipelines-controller --replicas=3
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
added support to change `disable-ha` and `buckets` in https://tekton.dev/docs/pipelines/enabling-ha/
added support to change performance configurations from https://tekton.dev/docs/pipelines/tekton-controller-performance-configuration/
Performance configuration fields: `kube-api-qps`, `kube-api-burst`, `threads-per-controller`
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow
Looks good to me 🎉

**Comment by jkandasa** [comment]
/cc @mramendi
added documentation for pipelines controller performance parameters

**Pull request merged**
