### PR TITLE
Adds short names to Operator CRDs

### PR DESCRIPTION
**Pull request by sm43**
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by piyush-garg** [comment]
Any reason to no to do for chain and result ?

**Comment by vdemeester** [comment]
any reason to do that ? `tc`, `tp` are not really.. conveying any meaning 😅

**Comment by sm43** [comment]
@piyush-garg couldn't think of shortnames for them. tc take for tektonconfig and tr is for taskrun i guess, didn't wanted to conflict.

@vdemeester those help while development a bit 🙃 even if they doesn't help much for the end user

**Comment by sm43** [comment]
@vdemeester do you think we shouldn't add this? 😄 
I could make my life easier with some bash .. so I am too strong adding this 
but still this would be helpful 😝

**Comment by vdemeester** [comment]
> @vdemeester do you think we shouldn't add this? smile I could make my life easier with some bash .. so I am too strong adding this but still this would be helpful stuck_out_tongue_closed_eyes

I don't really have strong opinions. I tend to "dislike" most shortnames because they can conflict with each others and they tend to be so short you don't really know what it's about (e.g. `tp` could mean *a lot of thing*).

They are somewhat useful, only when interactively with `kubectl`, and when you don't have completion setup. In bash script, it's usually better to use long names (and long command line) to be more descriptive and clearer when reading.

But in any case, I am fine getting this in, I am just not a fan of it 😝.

/approve

**Comment by piyush-garg** [comment]
i am also not sure if we should merge this if it not giving any value to end users and also inconsistent as some of the CRDs does not have short names (chains and results)

**Comment by sm43** [comment]
well not useful to end user and the short names could be conflicting
so I will make my life easier with bash for now 😄  
/close

**Pull request closed without merging**
