### PR TITLE
Added filesystem-custom-path to allowed x509 fulcio providers

### PR DESCRIPTION
**Pull request by sabre1041**
# Changes

Added filesystem-custom-path to allowed x509 fulcio providers for Tekton Chains

Relevant PR: https://github.com/tektoncd/chains/pull/727/

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Adds "filesystem-custom-path" to the list of allowed Chains Fulcio x509 providers
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @PuneetPunamiya @concaf

**Comment by jkandasa** [comment]
@sabre1041 we are going to revert this change via #2030, If you have a concern please start a discussion

**Comment by sabre1041** [comment]
I am good with reverting. Under the covers, this option is used but it is not exposed

**Pull request merged**
