### PR TITLE
ArtifactsPipelineRunEnableDeepInspection making this field to accept both bool and string

### PR DESCRIPTION
**Pull request by rupalibehera**
# Changes
https://issues.redhat.com/browse/SRVKP-4387

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by rupalibehera** [comment]
@PuneetPunamiya does this make sense ?

**Comment by rupalibehera** [comment]
I have tested this with upgrading and it is working fine.

**Comment by jkandasa** [comment]
@rupalibehera can you please rebase 2 commits to one?

**Review by jkandasa — APPROVED** [review]

**Comment by piyush-garg** [comment]
@rupalibehera @PuneetPunamiya can you please give detail about why this change in required in commit message, and also is it required for all the three fields?

**Comment by rupalibehera** [comment]
> @rupalibehera can you please rebase 2 commits to one?

done

**Comment by piyush-garg** [comment]
Also can we add some unit tests for this?

**Comment by rupalibehera** [comment]
> @rupalibehera @PuneetPunamiya can you please give detail about why this change in required in commit message, and also is it required for all the three fields?

some boolean fields in tekton config for chains were string and some were boolean, while adding those it was like a guess work if it should be bool or string hence I have updated it, it was required only for one field https://issues.redhat.com/browse/SRVKP-4387 but I added for all others as well

**Comment by rupalibehera** [comment]
> Also can we add some unit tests for this?

we do not have any existing unit tests for the same

**Comment by piyush-garg** [comment]
> > @rupalibehera @PuneetPunamiya can you please give detail about why this change in required in commit message, and also is it required for all the three fields?
> 
> some boolean fields in tekton config for chains were string and some were boolean, while adding those it was like a guess work if it should be bool or string hence I have updated it, it was required only for one field https://issues.redhat.com/browse/SRVKP-4387 but I added for all others as well

AFAIK, we do this when a field which was supposed to be boolean before, now is string, so to support upgrade, which change it like this to support both type/values. If this is the case here, please do this for the field which has got this change. Also, we should add validation defaulting etc accordingly. Also, good to have unit tests if you can add.

If this is not the case, and there is some other use case for this, can you please give details for that. Also, would be great if you can put all those details in commit msg and PR

**Comment by rupalibehera** [comment]
@piyush-garg @jkandasa I am just changing ArtifactsPipelineRunEnableDeepInspection field now and dropped the other fields.

**Comment by rupalibehera** [comment]
@piyush-garg @jkandasa , can we please merge this without the unit tests, there are very minimal changes now

**Pull request merged**
