### PR TITLE
Update tektoncd/pipeline to 0.45.0

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

EmbeddedStatus configuration is no more, so defaulting to empty as we
won't use / generate it.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Bump tektoncd/pipeline to 0.45.0 (and dependencies)
```

### CODE REVIEW

**Comment by PuneetPunamiya** [comment]
LGTM

**Review by jkandasa — APPROVED** [review]
LGTM
adding the pipeline ticket for the future reference: https://github.com/tektoncd/pipeline/pull/6049

**Review by concaf — APPROVED** [review]
/lgtm

**Pull request merged**
