### PR TITLE
[main] make options 'disabled' field as pointer to reduce the noise on TektonConfig CR

### PR DESCRIPTION
**Pull request by jkandasa**
# Changes

* in `TektonConfig` CR, under the `options` the field `disabled` is marked as `false` on newly created CRs. We see `disabled: false` under `options` on all the components. This looks like too noisy. So converting the filed `disabled` to pointer, now this field will be disappeared (only on new installation) and TektonConfig CR looks neat and clean. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
PR looks good, i hope it will not break upgrades

**Comment by jkandasa** [comment]
> PR looks good, i hope it will not break upgrades

@piyush-garg this will not break the upgrade. there is not difference on the CR YAML

**Pull request merged**
