### PR TITLE
Fix TektonResult read access

### LINKED ISSUE #1726: TektonResult can't be access by system:authenticated user
# Expected Behavior
system:authenticated user should be able to access `TektonResult`
# Actual Behavior
```
Error from server (Forbidden): tektonresults.operator.tekton.dev is forbidden: User "developer" cannot list resource "tektonresults" in API group "operator.tekton.dev" at the cluster scope
```
# Steps to Reproduce the Problem

1. Install operator
2. Create TektonResult CR

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

### PR DESCRIPTION
**Pull request by khrm**
There's a typo and it's not present in kustomization.yaml.

Fixes #1726
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/assign @jkandasa @concaf @PuneetPunamiya

**Comment by khrm** [comment]
Strange. It's asking for rebase when there's no changes in code.

**Review by concaf — APPROVED** [review]
/lgtm

**Pull request merged**
