### PR TITLE
Handling changing label in addon

### PR DESCRIPTION
**Pull request by vincent-pli**
# Changes
Avoid upgrade failed when changes of labels occurred in `Deployment`.
Same implements as https://github.com/tektoncd/operator/pull/112

The original issue: https://github.com/tektoncd/operator/issues/88

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
In upgrade case, with new version of `tekton`: `pipeline` or `addon`s, if new labels that were added to the `deployments`, 
will cause `field is immutable` exception, the PR can handle it and make the upgrade success.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
(we are gonna need to have a `release-note` for this :angel: )

**Comment by nikhil-thomas** [comment]
/lgtm

@vincent-pli could you add a `release note` section in your pr description.

**Comment by vincent-pli** [comment]
@vdemeester @nikhil-thomas 
Release node added, thanks

**Pull request merged**
