### PR TITLE
Bump tkn to 0.24.1 in ConsoleCLIDownload

### PR DESCRIPTION
**Pull request by rupalibehera**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by rupalibehera** [comment]
cc @piyush-garg

**Review by vdemeester — APPROVED** [review]

**Comment by rupalibehera** [comment]
@piyush-garg is there a way we can skip this integration test failure check because the failure is an infra issue.

**Pull request merged**
