### PR TITLE
Fix PAC config not handling hub catalogs

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix the issue of PAC config not able
to set default hub catalog value and also
additional hub catalog value in configmap

Bump PAC to v0.27.1

Add tests
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Fix PAC config not handling hub catalogs
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
/hold

PR is good to review, just that I need to replace my fork to PAC release in go.mod after https://github.com/openshift-pipelines/pipelines-as-code/pull/1703 is merged and new release is cut.

**Review by jkandasa — APPROVED** [review]

**Comment by jkhelil** [comment]
@piyush-garg it is worth seperating bump/vendor commit from the fix itself

**Review by jkhelil — APPROVED** [review]

**Pull request merged**
