### PR TITLE
fix: major bugs in addon_controller.go

### PR DESCRIPTION
**Pull request by timmyers**
# Changes

Code was relying on refreshCR function to update the CR during reconciliation. This does not work becaues the operator SDk client uses a cache so this is almost always out of date, resulting in tons of errors as we resources are updated with stale resource versions. Remove all use of that and instead rely on the fact that client Update() calls will update the CR pointer correctly. Updating operator-sdk and deps in #79 fixed the bug that was mentioned in a comment where GroupVersionKind is lost.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by timmyers** [comment]
There shouldn't be an update with more than one `update` in a reconcile loop.  The `update` function modifies the CR object that is passed to it.

From the `controller-runtime` package:
```
// Update updates the given obj in the Kubernetes cluster. obj must be a
// struct pointer so that obj can be updated with the content returned by the Server.
```

**Comment by vincent-pli** [comment]
@timmyers 
Yes, but when run `update`, the `resource version` will changed, if more than one `update` in once `reconcile` the subsequent `update` will hit `version` issue, since it based on a stale resource version(since in one `reconcile`).
Correct me if I missing something, thanks

**Comment by timmyers** [comment]
`r.client.Update` will update the resource version on the CR so you can use it multiple times in a row i.e.:

```
func (r *ReconcileAddon) test(res *op.Addon) {
	fmt.Println(res.ResourceVersion) // 1
	r.client.Update(context.TODO(), res) // Updates res.ResourceVersion if successful
	fmt.Println(res.ResourceVersion) // 2
}
```

**Comment by vincent-pli** [comment]
@timmyers 
I think you are right, maybe that different between pure `client-go` and `controller-runtime`, thanks.

/lgtm
/approve

**Comment by nikhil-thomas** [comment]
cc @sthaha

**Comment by sthaha** [comment]
/lgtm 
/meow 
❤️

**Comment by sthaha** [comment]
@timmyers we need the CLA to be signed 🙏

**Comment by timmyers** [comment]
Trying to figure out how to sign the new CLA...

**Comment by timmyers** [comment]
@sthaha I had to push a whitespace comment change to trigger the CLA bot, will need a new LGTM 🙏

**Pull request merged**
