### PR TITLE
[cherry-pick] 0.50.x Improving TektonAddon upgrade

### PR DESCRIPTION
**Pull request by nikhil-thomas**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
/hold
pending e2e tests verification on OpenShift

**Review by vdemeester — APPROVED** [review]

**Comment by nikhil-thomas** [comment]
:technologist: :point_right: **hold** until we verify whether we need https://github.com/tektoncd/pipeline/pull/4269 in the tektoncd/pipeline release (v0.28.x) we ship with v0.50.x (1.6.x)

**Comment by nikhil-thomas** [comment]
nevermind it is handled as part of `create-release-branch` script in midstream https://github.com/openshift/tektoncd-operator/commit/fadfbe4d43ddf66f360a4d93dd23fda4f970c052

so removing hold

**Pull request merged**
