### PR TITLE
Remove kubeconfigwriter reference from the CSV

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This image is not published anymore from tektoncd/pipeline, so we don't need to handle it anymore.

cc @piyush-garg @concaf @jkandasa @rupalibehera 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by PuneetPunamiya** [comment]
LGTM

**Review by jkandasa — APPROVED** [review]
LGTM

**Comment by jkandasa** [comment]
@vdemeester I see an entry here https://github.com/tektoncd/operator/blob/502601ec1754e2cf637d448624e5da2ccb2860f5/operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml#L889

Is it not required to remove?

**Comment by vdemeester** [comment]
@jkandasa oh I might have missed one 😅

**Comment by vdemeester** [comment]
Updated 👼🏼

**Pull request merged**
