### PR TITLE
Update/cluster tasks

### PR DESCRIPTION
**Pull request by nikhil-thomas**
# Main Changes

- [X] move tasks from openshift/pipelines-catalog into openshift/kodata/../../source-local
    - [X] remove openshift/pipelines-catalog tasks from fetch task mechanism
- [X] use the fetch task script only to fetch task from tektoncd/catalog 
- [X] use the fetch task script only to download the task into openshift/kodata/../../source-external (downloaded when along with other payload fetch)
    - [X] the fetch task script does not changte Taks kind to ClusterTask
    - [X] the fetch task script does not create a versioned ClusterTask (task with version in its name
- [X] operator changes the type of tasks in source-local and source-external from Task to ClusterTask just before installation
- [X] operator creates versioned versions of ClusterTasks during installation based on version information obtained from environment variable

- [X] Add image replacement environment variables for clusterTasks in operator controller deployment
  - pinning versions of skopeo-copy, kn images can be done once for each release branch
- [X] Add a scrpt to find latest sha for latest releases of step images like buildah, s2i, skope-copy and kn

note: all tektoncd/catalog tasks are pulled from main branch. the version subfolder in the catalog organization should ensure the interface remains the same. The content of the tasks downloaded can be freezed per release branch. 

# Changes

[OpenShift] Improve Addon Task management

Move logic to create 'versioned clustertasks' (clustertasks with version
suffix in names), into operator

Move kind replacement of all tasks into operator

Move tasks from (openshift) pipelines-catalog into operator openshift
kodata

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@piyush-garg @concaf

**Review by vdemeester — APPROVED** [review]

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Pull request merged**
