### PR TITLE
[cherry-pick] Catch generate_bundle() error and exit

### PR DESCRIPTION
**Pull request by concaf**
# Changes

Cherry pick #668 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by concaf** [comment]
won't work but let's try
/lgtm

**Comment by sm43** [comment]
/lgtm
😄

**Pull request merged**
