### PR TITLE
Adds Tekton Hub ownerRef for Hub components

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
- Currently, there is no ownerRef added for secrets and configMap
of db, api and ui

- This patch adds an ownerRef of `TektonHub` when Hub instance is
created

 **Note** : If the secrets of db and api are created by user then those
one's are not deleted

Signed-off-by: Puneet Punamiya ppunamiy@redhat.com

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@PuneetPunamiya add a release not section in your pr description.
if it does not need one, the add the release note section. (as mentioned at the end of pr template).

**Review by vdemeester — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
