### PR TITLE
Run rbac createresources for namespaces concurrently to avoid slowness

### PR DESCRIPTION
**Pull request by jkhelil**
# Changes
- Process rbac resource creation for openshift namespace reconciliation concurrently to avoid slowness on clusters with high number of namespace
- Avoid blocking the reconciliation loop on error, when errors happen on namespace rbac resource reconciliation for openshift
- Add unit tests to createRessource in rbac.go  

depends on https://github.com/tektoncd/operator/pull/2217

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by vdemeester** [comment]
Seems like the `vendor` folder is not up-to-date or something.

**Comment by jkhelil** [comment]
@piyush-garg unit tests are failing. My understading is that we need go-licenses@v1.0.0 , and seems to be installed at ci level or plumbing level ?
WDYT?

**Comment by vdemeester** [comment]
> @piyush-garg unit tests are failing. My understading is that we need go-licenses@v1.0.0 , and seems to be installed at ci level or plumbing level ? WDYT?

I wonder why are we getting this now though ? What changed ? Is it happening in all CI jobs ?
Looking back at the failure, it seems to be on the `toolchain` package. Maybe removing the `toolchain` line in `go.mod` would fix the problem for now ?

**Comment by vdemeester** [comment]
> Looking back at the failure, it seems to be on the `toolchain` package. Maybe removing the `toolchain` line in `go.mod` would fix the problem for now ?

If that fixes it, we need to figure that one out, in `tektoncd/plumbing` or per repositories indeed, because it will keep coming back I think.

**Comment by jkhelil** [comment]
> > Looking back at the failure, it seems to be on the `toolchain` package. Maybe removing the `toolchain` line in `go.mod` would fix the problem for now ?
> 
> If that fixes it, we need to figure that one out, in `tektoncd/plumbing` or per repositories indeed, because it will keep coming back I think.

Seems fixed for now by removing the toolchain directive
Thanks @vdemeester

**Review by vdemeester — APPROVED** [review]

**Pull request closed without merging**
