### PR TITLE
Update proxy reconciller for empty value env

### PR DESCRIPTION
**Pull request by piyush-garg**
This will update proxy reconciler to not update container spec
if the value is empty and also remove the env from container spec
if it already exists

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Update proxy reconciller for empty value env
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by vdemeester** [comment]
cc @nikhil-thomas

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
