### PR TITLE
update pac version to 0.5.6

### PR DESCRIPTION
**Pull request by sm43**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by concaf — CHANGES_REQUESTED** [review]
Could you also make changes per these PRs: #732 (release branch) #731 (main branch) #730 (release branch)

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Review by savitaashture — APPROVED** [review]
:tada:

**Pull request merged**
