### PR TITLE
Small spelling fix

### PR DESCRIPTION
**Pull request by Trimeego**
Just noticed this and thought it would be an easy PR.  No functionality changes or tests needed, just a typo :)

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by pradeepitm12** [comment]
@Trimeego Thanks for the PR :+1:
You need to sign the CLA, which can be done following [this ](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/8049964/196359824/611/#/?version=2)
Please feel free to ping.

**Comment by piyush-garg** [comment]
@Trimeego Can you please do the CLA signing

**Comment by nikhil-thomas** [comment]
/retest

as https://github.com/tektoncd/operator/pull/769 has merged, ci should pass

**Pull request closed without merging**
