### PR TITLE
Add list nodes rule for kubernetes-rbac

### PR DESCRIPTION
**Pull request by uqix**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by jkandasa** [comment]
@uqix thanks for the PR. can your please explain, where do you required nodes list permission in operator?

**Comment by uqix** [comment]
@jkandasa I'm confused too, while the resources (`$ kubectl apply -f https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml`) do include this permission (list nodes).

**Comment by cmorinupgrade** [comment]
That means this must be backported to the helm chart: https://github.com/tektoncd/operator/blob/main/chart/templates/kubernetes-rbac.yaml

**Comment by cmorinupgrade** [comment]
The helm chart should definitely match the rbac that we can find on the manifest from `https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml`.

**Comment by jkandasa** [comment]
fixes #1757

**Review by jkandasa — APPROVED** [review]
/lgtm

**Comment by jkandasa** [comment]
cc @vdemeester

**Pull request merged**
