### PR TITLE
Remove --no-cache from buildah as no longer necessary

### PR DESCRIPTION
**Pull request by jimmyjones2**
# Changes

Port of tektoncd/catalog#1230 (buildah task 0.7)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by piyush-garg** [comment]
Hey @jimmyjones2 

Can you provide an explanation for this

**Comment by jimmyjones2** [comment]
In tektoncd/catalog#265 the option `--no-cache` was added unconditionally as a buildah arguments, due to confusion around the `--layers` argument which was removed at the same time and was the real culprit. I've verified this with a simple Dockerfile:

`buildah bud` - consistently 9s
`buildah bud --no-cache` - consistently 9s
`buildah bud --layers` - 39s first run, subsequent 1s

Therefore `--no-cache` is no longer required. Having this option present, prevents the user from taking advantage of buildah's distributed cache (by setting `--cache-to` and `--cache-from` in `BUILD_EXTRA_ARGS`)

**Pull request merged**
