### PR TITLE
Bump pac and cli versions

### PR DESCRIPTION
**Pull request by piyush-garg**
This will bump pac and cli versions
which will be shipped with 0.63.x release

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Bump pac and cli versions
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm
/hold

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Comment by piyush-garg** [comment]
/hold cancel
as the cli release is done now

**Pull request merged**
