### PR TITLE
Add quickstart for configuring pipeline metrics levels

### PR DESCRIPTION
**Pull request by karthikjeeyar**
# Changes

Add Quickstart to guide the users to configure the pipeline metric level.

image

---
image

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

None

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@khrm

**Comment by nikhil-thomas** [comment]
@karthikjeeyar could you fix these yaml lints
```bash
./cmd/openshift/operator/kodata/tekton-addon/optional/quickstarts/configure-pipeline-metrics-quickstart-yaml
  27:68     error    trailing spaces  (trailing-spaces)
  57:59     error    trailing spaces  (trailing-spaces)
  61:25     error    trailing spaces  (trailing-spaces)
  64:30     error    trailing spaces  (trailing-spaces)
```

**Comment by khrm** [comment]
Isn't this Quickstart encouraging a user to change the value to run level. Is this OK, @vdemeester?

**Comment by nikhil-thomas** [comment]
> Isn't this Quickstart encouraging a user to change the value to run level. Is this OK, @vdemeester?

@khrm
let us wait until we resolve this 🧑‍💻 

fyi: the 2 cherry-picks merged already
- https://github.com/tektoncd/operator/pull/803
- https://github.com/tektoncd/operator/pull/804

**Comment by khrm** [comment]
@karthikjeeyar Will you add a disclaimer in this quickstart?

**Comment by karthikjeeyar** [comment]
@khrm I have added disclaimer in the QS as well and created patches for the same in 0.50.x, 0.55.x 

https://github.com/tektoncd/operator/pull/807
https://github.com/tektoncd/operator/pull/808

**Review by khrm — APPROVED** [review]

**Pull request merged**
