### PR TITLE
addons/clustertasks: update images to latest...

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Updating to latest redhat supported buildah image

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Buildah cluster task default builder image updated to 8.5-12
```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
/hold

looks like there is an already existing practice to handle this.

[this script](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/hack/openshift/update-image-sha.sh#L80):
1. finds the latest version of official release (Red Hat) of a given image
2. find the sha from the tag
3. replaces the tag in [operator.yaml](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/config/openshift/base/operator.yaml#L69) and in csv config ([here](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/operatorhub/openshift/config.yaml#L129) and [here](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/operatorhub/openshift/config.yaml#L217))

so even if we change the sha in the task, the operator will override them with the sha provided in the envs.

Looks like all we need to do is to run this script once ([usage](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/hack/openshift/update-image-sha.sh#L36)),

**Comment by vdemeester** [comment]
> /hold
> 
> looks like there is an already existing practice to handle this.
> 
> [this script](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/hack/openshift/update-image-sha.sh#L80):
> 
> 1. finds the latest version of official release (Red Hat) of a given image
> 2. find the sha from the tag
> 3. replaces the tag in [operator.yaml](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/config/openshift/base/operator.yaml#L69) and in csv config ([here](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/operatorhub/openshift/config.yaml#L129) and [here](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/operatorhub/openshift/config.yaml#L217))
> 
> so even if we change the sha in the task, the operator will override them with the sha provided in the envs.
> 
> Looks like all we need to do is to run this script once ([usage](https://github.com/tektoncd/operator/blob/fd58ba044402e63455b26158f8cfddc27af931b6/hack/openshift/update-image-sha.sh#L36)),

@nikhil-thomas thanks I will look into it **but**, we should also make sure those files are updated in-place (the one in source-local). The main reason for it is, if we modify it and want to try it, without installing the operator, we should be up-to-date or relatively close to what the operator will "replace".

**Comment by vdemeester** [comment]
We also need to ensure we run this prior to releases (and test it prior to release as well).

**Comment by nikhil-thomas** [comment]
as https://github.com/tektoncd/operator/pull/769 has merged, ci should pass

**Pull request merged**
