### PR TITLE
Moves `default-forbidden-env` to optional Pipelines properties

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
- Initially the field `default-forbidden-env` was added as a part
of `feature-flag` configMap whereas it has to be included in
`config-defaults` configMap

- Hence, this patch moves the field to optional Pipelines properties
struct so that the field gets added in `config-defaults` configMap

Signed-off-by: Puneet Punamiya ppunamiy@redhat.com

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by concaf — COMMENTED** [review]
@PuneetPunamiya can you update the commit message to reflect why was this done?

**Review by vdemeester — APPROVED** [review]

**Review by concaf — APPROVED** [review]
/lgtm

**Pull request merged**
