### PR TITLE
Add chains image env for openshift

### PR DESCRIPTION
**Pull request by piyush-garg**
This will add the env in config.yaml for generating csv
on OpenShift so that the redhat build image can refelect
in csv and replaced during installation

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by concaf — COMMENTED** [review]
Do we also need to add the env here? https://github.com/tektoncd/operator/blob/main/operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml

**Comment by piyush-garg** [comment]
> Do we also need to add the env here? https://github.com/tektoncd/operator/blob/main/operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml

This is the generated on using config, we don't need to add here afaik. cc @nikhil-thomas

**Review by vdemeester — APPROVED** [review]

**Comment by nikhil-thomas** [comment]
> This is the generated one using config, we don't need to add here afaik. cc @nikhil-thomas

yes that is right.

However, if you want you can generate the csv and push wiht this pr. So that it will serve as a reference. Also it will be a check.

**Comment by concaf** [comment]
@nikhil-thomas thanks, so let's let it get auto-generated!?
/lgtm

**Pull request merged**
