### PR TITLE
Revert https://github.com/tektoncd/operator/pull/1271

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
Reverting #1271 as we have fix for PAC watcher issue https://github.com/openshift-pipelines/pipelines-as-code/pull/1135

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
👯 
@savitaashture can you link the pipelines-as-code PR that fixes that in there as well ?

**Comment by savitaashture** [comment]
> dancers @savitaashture can you link the pipelines-as-code PR that fixes that in there as well ?

Sure added PAC PR link in description and added Operator PR link over PAC PR

**Pull request merged**
