### PR TITLE
Move platform defaulting to webhook and avoid api calls in reconciler 

### PR DESCRIPTION
**Pull request by sm43**
after #1070 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
Not that, if the webhook is not working for some reason (or not ready yet), we may end up with failure

**Comment by sm43** [comment]
> Not that, if the webhook is not working for some reason (or not ready yet), we may end up with failure

yep if webhook is down then user won't be able to edit it.
but we do call defaulting from reconciler, platform specific defaulting will take place even if webhook is down for already created CR

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Pull request merged**
