### PR TITLE
Update git-init image

### PR DESCRIPTION
**Pull request by pratap0007**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
This updates git-init image
```

### CODE REVIEW

**Review by concaf — APPROVED** [review]
/lgtm

**Comment by jkandasa** [comment]
@pratap0007 don't we need this to `main` ?

**Comment by pratap0007** [comment]
> @pratap0007 don't we need this to `main` ?

we need  this for main as well

**Pull request merged**
