### PR TITLE
Correct the operator name in Dockerfile

### PR DESCRIPTION
**Pull request by zhangtbj**
When I build the operator image by using operator-sdk, I got an error:
```
✔ $ operator-sdk build docker.io/xxx:latest
INFO[0000] Building OCI image docker.io/xxx:latest
Sending build context to Docker daemon  86.06MB
Step 1/8 : FROM registry.access.redhat.com/ubi7/ubi-minimal:latest
 ---> 689f32e7a418
Step 2/8 : ENV OPERATOR=/usr/local/bin/tekton-operator     USER_UID=1001     USER_NAME=tekton-operator
 ---> Using cache
 ---> eaba9c1da915
Step 3/8 : COPY build/_output/bin/operator ${OPERATOR}
COPY failed: stat /var/lib/docker/tmp/docker-builder408503672/build/_output/bin/operator: no such file or directory
Error: failed to output build image us.icr.io/tknoperator/openshift-pipelines-operator:latest: (failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "us.icr.io/tknoperator/openshift-pipelines-operator:latest", "."}: exit status 1)
Usage:
  operator-sdk build <image> [flags]

Flags:
      --go-build-args string      Extra Go build arguments as one string such as "-ldflags -X=main.xyz=abc"
  -h, --help                      help for build
      --image-build-args string   Extra image build arguments as one string such as "--build-arg https_proxy=$https_proxy"
      --image-builder string      Tool to build OCI images. One of: [docker, podman, buildah] (default "docker")

Global Flags:
      --verbose   Enable verbose logging
```

Then I found there is a bug that the operator name is not match. Fix by using this PR. Please review!

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by vincent-pli** [comment]
@zhangtbj 
Interesting, no such issue in my env, could you append more details, such as steps or version of `operator sdk`.

**Comment by zhangtbj** [comment]
Hi @vincent-pli ,

My info:
OPERATORSDK_RELEASE_VERSION=v0.12.0

And this is my script:
```
# Install operator-sdk
OPERATORSDK_RELEASE_VERSION=v0.12.0
curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATORSDK_RELEASE_VERSION}/operator-sdk-${OPERATORSDK_RELEASE_VERSION}-x86_64-linux-gnu
chmod +x operator-sdk-${OPERATORSDK_RELEASE_VERSION}-x86_64-linux-gnu && mv operator-sdk-${OPERATORSDK_RELEASE_VERSION}-x86_64-linux-gnu operator-sdk

IMAGE_URL="us.icr.io/tknoperator-build/openshift-pipelines-operator:latest"
IMAGE_URL_SED="us.icr.io\/tknoperator-build\/openshift-pipelines-operator:latest"
./operator-sdk build ${IMAGE_URL}
docker push ${IMAGE_URL}
```

I ran in Travis with ubuntu container but fail. You can also have a try that.

Thanks!

**Comment by vincent-pli** [comment]
@zhangtbj 
Finally, I know what's  going on. I think you clone the repo to `tekton-operator` rather than `operator`, use folder `operator` the issue will gone.

**Comment by sthaha** [comment]
I feel this is an issue almost everyone will run into thus having a solution that works independent of the directory name will be great!

**Comment by zhangtbj** [comment]
Oh, I see. yes, I used the `tekton-operator` name.

Let me switch to `operator` folder.

But does the operator-sdk build depends on the folder name?

I modified the folder name because we have many operators like knative serving or eventing operator in same path.

Thanks!

**Comment by vincent-pli** [comment]
@sthaha 
Agree with you, it's surprise `operator sdk` work depends on the folder name.

**Comment by zhangtbj** [comment]
Thanks anyway! Let me close this PR first as correct folder name works for me.

Thanks!

**Pull request closed without merging**
