### PR TITLE
fix: helm chart fail when set Values.operator.operatorName

### PR DESCRIPTION
**Pull request by Abirdcfly**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
lgtm cc @jkandasa @vdemeester

**Review by jkandasa — APPROVED** [review]
LGTM

**Comment by jacksgt** [comment]
Thanks for finding this! 

/approve

**Pull request merged**
