### PR TITLE
Documentation aesthetics - removed the excess ``` backticks from fenced code block after rendering

### PR DESCRIPTION
**Pull request by arnoldmashava**
The desired output after remediations:

```
$ kubectl apply -f https://raw.githubusercontent.com/tektoncd/operator/main/config/crs/kubernetes/config/all/operator_v1alpha1_config_cr.yaml
```
Resolves [Issue 596](https://github.com/tektoncd/website/issues/596) after approval by the powers-that-be @AlanGreene

### CODE REVIEW

**Comment by AlanGreene** [comment]
Thanks for the PR @arnoldmashava, however I'm not a maintainer on this repo so I won't be able to approve it.

There are some additional things you will need to take care of though. Please use the PR description template and provide the required content. You will also need a signed CLA (either as an individual or for your employer), see https://github.com/tektoncd/operator/pull/2047#issuecomment-1991958161

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Comment by khrm** [comment]
@arnoldmashava  Please sign the cla.

**Comment by arnoldmashava** [comment]
> [CLA Signed](https://easycla.lfx.linuxfoundation.org/#/?version=2)
> 
> * ✅login: arnoldmashava / ([4dade29](https://github.com/tektoncd/operator/commit/4dade29db88984bce84511cf8f8ee6feed1504b0))
> 
> 
> The committers listed above are authorized under a signed CLA.

Updated @khrm

**Review by jkandasa — APPROVED** [review]
/lgtm

Thanks for the contribution @arnoldmashava :tada:

**Comment by arnoldmashava** [comment]
> /lgtm
> 
> Thanks for the contribution @arnoldmashava 🎉

Heartfeltly acknowledged @jkandasa

```dart
>_ sudo ¡Muchas Gracias! --verbose
```

**Pull request merged**
