### PR TITLE
[openshift] Add ubi-minimal to fetch-latest-sha script

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Add `registry.redhat.io/ubi8/ubi-minimal` to the list of images for
which latest sha needs to be looked up

Expose `maven-settings` step image in maven task as an environment
variable in operator depoloyment

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by sm43** [comment]
do we have a transformer in place for
`Expose maven-settings step image in maven task as an environment
variable in operator depoloyment`?

**Review by vdemeester — APPROVED** [review]

**Comment by nikhil-thomas** [comment]
> do we have a transformer in place for `Expose maven-settings step image in maven task as an environment variable in operator depoloyment`?

one thing we did right is to keep our step and param transformation generic. So for this adding the env is sufficient.

I manual tested on OpenShift 4.10. I works.

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
