### PR TITLE
[release-0.50.x] Add a warning message for changing metrics level configuration

### PR DESCRIPTION
**Pull request by karthikjeeyar**
# Changes

Add Quickstart warning message while re-configuring the pipeline metric level.

image

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

None

### CODE REVIEW

**Review by khrm — APPROVED** [review]

**Review by concaf — APPROVED** [review]
/approve
/lgtm

**Comment by concaf** [comment]
ah crap, I cannot approve for this branch

**Review by savitaashture — APPROVED** [review]
:tada:

**Pull request merged**
