### PR TITLE
openshift: update all image references

### PR DESCRIPTION
**Pull request by yselkowitz**
# Changes

Update all image references in the OpenShift operator.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/ok-to-test
/cc @sm43 @piyush-garg @concaf

**Comment by piyush-garg** [comment]
/hold cancel

we discussed to take new sha for images

**Pull request merged**
