### PR TITLE
s2i ClusterTask: option to provide container registry credentials in a workspace

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
s2i ClusterTask: option to provide container registry credentials in a workspace
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by piyush-garg** [comment]
@zroubalik Should we do the same for buildah task too, to keep it consistent across all

**Comment by piyush-garg** [comment]
And should we set the env based on whether the workspace is bound or not? What is the current value of `DOCKER_CONFIG` env and if the workspace is not provided, what value getting assigned, and is it getting changed?

**Comment by vdemeester** [comment]
> And should we set the env based on whether the workspace is bound or not? What is the current value of `DOCKER_CONFIG` env and if the workspace is not provided, what value getting assigned, and is it getting changed?

@piyush-garg you mean something where we would use env variables `WORKSPACE_DOCKER_CONFIG_PATH` and `WORKSPACE_DOCKER_CONFIG_BOUND` and do something similar to what `git-clone` does on the catalog (see [here](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.7/git-clone.yaml#L189)). I think that would make sense.

**Comment by zroubalik** [comment]
> @zroubalik Should we do the same for buildah task too, to keep it consistent across all

@vdemeester @piyush-garg should I open a separate PR for that?

**Comment by piyush-garg** [comment]
> > @zroubalik Should we do the same for buildah task too, to keep it consistent across all
> 
> @vdemeester @piyush-garg should I open a separate PR for that?

doing in the same PR is also fine here

**Comment by piyush-garg** [comment]
> > And should we set the env based on whether the workspace is bound or not? What is the current value of `DOCKER_CONFIG` env and if the workspace is not provided, what value getting assigned, and is it getting changed?
> 
> @piyush-garg you mean something where we would use env variables `WORKSPACE_DOCKER_CONFIG_PATH` and `WORKSPACE_DOCKER_CONFIG_BOUND` and do something similar to what `git-clone` does on the catalog (see [here](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.7/git-clone.yaml#L189)). I think that would make sense.

Yes that's what I mean, either like git clone or like buildah here https://github.com/tektoncd/catalog/blob/main/task/buildah/0.4/buildah.yaml#L69, it will not set the DOCKER_CONFIG to `""` and backward comptability will be maintained.

**Comment by zroubalik** [comment]
> > > And should we set the env based on whether the workspace is bound or not? What is the current value of `DOCKER_CONFIG` env and if the workspace is not provided, what value getting assigned, and is it getting changed?
> > 
> > 
> > @piyush-garg you mean something where we would use env variables `WORKSPACE_DOCKER_CONFIG_PATH` and `WORKSPACE_DOCKER_CONFIG_BOUND` and do something similar to what `git-clone` does on the catalog (see [here](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.7/git-clone.yaml#L189)). I think that would make sense.
> 
> Yes that's what I mean, either like git clone or like buildah here https://github.com/tektoncd/catalog/blob/main/task/buildah/0.4/buildah.yaml#L69, it will not set the DOCKER_CONFIG to something else may be `""` and backward compatibility will be maintained by not changing the default value.

This Task is not using `script` as the other Tasks but  `command` to directly call buildah. Should I convert this task to use `script` or is there any other way how to address this?

**Comment by zroubalik** [comment]
@

> This Task is not using `script` as the other Tasks but `command` to directly call buildah. Should I convert this task to use `script` or is there any other way how to address this?

@piyush-garg @vdemeester ^^

**Comment by piyush-garg** [comment]
> > > > And should we set the env based on whether the workspace is bound or not? What is the current value of `DOCKER_CONFIG` env and if the workspace is not provided, what value getting assigned, and is it getting changed?
> > > 
> > > 
> > > @piyush-garg you mean something where we would use env variables `WORKSPACE_DOCKER_CONFIG_PATH` and `WORKSPACE_DOCKER_CONFIG_BOUND` and do something similar to what `git-clone` does on the catalog (see [here](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.7/git-clone.yaml#L189)). I think that would make sense.
> > 
> > 
> > Yes that's what I mean, either like git clone or like buildah here https://github.com/tektoncd/catalog/blob/main/task/buildah/0.4/buildah.yaml#L69, it will not set the DOCKER_CONFIG to something else may be `""` and backward compatibility will be maintained by not changing the default value.
> 
> This Task is not using `script` as the other Tasks but `command` to directly call buildah. Should I convert this task to use `script` or is there any other way how to address this?

The change from command to the script is getting done with #904

**Comment by zroubalik** [comment]
> > > > > And should we set the env based on whether the workspace is bound or not? What is the current value of `DOCKER_CONFIG` env and if the workspace is not provided, what value getting assigned, and is it getting changed?
> > > > 
> > > > 
> > > > @piyush-garg you mean something where we would use env variables `WORKSPACE_DOCKER_CONFIG_PATH` and `WORKSPACE_DOCKER_CONFIG_BOUND` and do something similar to what `git-clone` does on the catalog (see [here](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.7/git-clone.yaml#L189)). I think that would make sense.
> > > 
> > > 
> > > Yes that's what I mean, either like git clone or like buildah here https://github.com/tektoncd/catalog/blob/main/task/buildah/0.4/buildah.yaml#L69, it will not set the DOCKER_CONFIG to something else may be `""` and backward compatibility will be maintained by not changing the default value.
> > 
> > 
> > This Task is not using `script` as the other Tasks but `command` to directly call buildah. Should I convert this task to use `script` or is there any other way how to address this?
> 
> The change from command to the script is getting done with #904

OK, so I will till it is merged, I hope we can make on time, so this change is included in the next release 🤞

**Comment by zroubalik** [comment]
@piyush-garg @vdemeester this PR should be ready, PTAL

**Review by vdemeester — APPROVED** [review]
/meow

**Comment by zroubalik** [comment]
> /meow

😸

**Comment by piyush-garg** [comment]
@zroubalik Should we do the same for buildah task too ?

**Comment by zroubalik** [comment]
> @zroubalik Should we do the same for buildah task too ?

@piyush-garg covered here: https://github.com/tektoncd/operator/pull/943

**Pull request merged**
