### PR TITLE
fix docs typo for addon clusterTasks

### PR DESCRIPTION
**Pull request by emanuelelevo**
# Changes

fix docs typo for addon clusterTasks

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by sm43** [comment]
@emanuelelevo Can you please sign the CLA so that we can merge this ? 🙂

**Comment by emanuelelevo** [comment]
> @emanuelelevo Can you please sign the CLA so that we can merge this ? slightly_smiling_face

signed, thanks

**Comment by vdemeester** [comment]
> > @emanuelelevo Can you please sign the CLA so that we can merge this ? slightly_smiling_face
> 
> signed, thanks

I think you might need to force-push the PR in order to make the check being fixed 😛 😓

**Comment by emanuelelevo** [comment]
> > > @emanuelelevo Can you please sign the CLA so that we can merge this ? slightly_smiling_face
> > 
> > 
> > signed, thanks
> 
> I think you might need to force-push the PR in order to make the check being fixed stuck_out_tongue sweat

the signature check doesn't seem to pass. I'll try to figure out what's wrong.

**Comment by nikhil-thomas** [comment]
/retest

as https://github.com/tektoncd/operator/pull/769 has merged, ci should pass

**Comment by emanuelelevo** [comment]
nothing, EasyCLA check still failing. i've signed this CLA about 8 times now. Feel free to close this PR.

**Pull request closed without merging**
