### PR TITLE
Update git-clone 0.4 task for 1.5.0

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Backporting https://github.com/tektoncd/catalog/pull/763, mainly for git-clone task

/cc @nikhil-thomas @pradeepitm12 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Comment by vdemeester** [comment]
/retest
For some reason jobs get killed...

**Pull request merged**
