### PR TITLE
[0.67.x] Fix Image Transforms for Results

### PR DESCRIPTION
**Pull request by khrm**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug
/release-note-none

**Comment by piyush-garg** [comment]
@khrm 

by default if no prefix it is used for deployment, if there is `JOB` prefix it is for jobs tranformer, and should we add something similar for statefulset ?

**Comment by khrm** [comment]
Does it make any difference? @jkandasa @vdemeester

**Review by vdemeester — APPROVED** [review]
I don't really know if it makes a difference, I think it's more "convention" than anything ?

**Review by jkandasa — APPROVED** [review]

**Pull request merged**
