### PR TITLE
Configure node selection for components using CR spec

### PR DESCRIPTION
**Pull request by sm43**
This provides fields in CR to customize the deployments of components
to select node using nodeselector or/and toleration.
Pass the values for nodeselector and toleration in spec of TektonConfig
CR which will be passed further to components and will get added in
deployments.

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

Provides fields `nodeSelector` and `toleration` in CR to configure node selection for pods created through operator. User can add the fields in TektonConfig CR and later operator will propagate it to the CRs created by it and add in all deployments created by it.

### CODE REVIEW

**Comment by sm43** [comment]
/cc @nikhil-thomas 
@piyush-garg 
@pradeepitm12

**Comment by nikhil-thomas** [comment]
@sm43 could you add a brief release note to the pr description.
Looks good to me. 👍 
Let us get additional reviews.

**Review by savitaashture — COMMENTED** [review]
/lgtm
Thank you :+1:

**Pull request merged**
