### PR TITLE
[main] update OpenShift bundle features annotations

### PR DESCRIPTION
**Pull request by jkandasa**
# Changes

* updates OpenShift CSV annotations
* OpenShift Doc about these flags: https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by jkandasa** [comment]
CC @rupalibehera

**Comment by rupalibehera** [comment]
This looks good, sorry for not doing it before I missed it

**Comment by savitaashture** [comment]
/lgtm

@jkandasa Can you add a link in the description referencing the source where you found this change

**Comment by jkandasa** [comment]
> /lgtm
> 
> @jkandasa Can you add a link in the description referencing the source where you found this change

Updated

**Pull request merged**
