### PR TITLE
Remove obsolete Config CRD instance cleanup job

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Remove Config CRD cleanup K8s job as it is was packaged with previous release. Therefore,
it is not needed in the upcoming release.

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by nikhil-thomas** [comment]
/hold 
test in progress (on openshift)

**Pull request merged**
