### PR TITLE
correct typo in code comments

### PR DESCRIPTION
**Pull request by wzhanw**
# Changes
Correct two typos in the code comments.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/ok-to-test

**Comment by sm43** [comment]
@wzhanw EasyCLA seems stuck 😅  Could you try re-pushing so that it will be triggered again?

**Comment by wzhanw** [comment]
@sm43  I found that and I repushed the commits. please check. Thank you

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Pull request merged**
