### PR TITLE
Add e2e tests for TektonPipeline install/uninstall

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Add install/uinstall and deployment recreate tests

Improve e2e test utils

Fix golang and yaml lint errors

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by savitaashture** [comment]
Looks good to me

@nikhil-thomas I assume this is first part of e2e 
I mean still we need to handle for remaining CRs, Upgrade, functionality related test in subsequent PR's right?

**Comment by nikhil-thomas** [comment]
> Looks good to me
> 
> @nikhil-thomas I assume this is first part of e2e
> I mean still we need to handle for remaining CRs, Upgrade, functionality related test in subsequent PR's right?

yup, exactly :+1:

**Pull request merged**
