### PR TITLE
Upgrade ConsoleYAMLSample apiVersion to Pipelines v1

### PR DESCRIPTION
**Pull request by jkhelil**
# Changes
Upgrade ConsoleYAMLSample apiVersion to Pipelines v1

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes
None

### CODE REVIEW

**Comment by piyush-garg** [comment]
there are some task snippets too, can you do check all and do the same

**Comment by piyush-garg** [comment]
/approve
cc @jkandasa

**Comment by jkhelil** [comment]
@jkandasa lgtm ?

**Pull request merged**
