### PR TITLE
Fix servicemonitor selectorLabels indentation in chart

### PR DESCRIPTION
**Pull request by davidumea**
# Changes

`selectorLabels` needed to be indented one step further in the `ServiceMonitor` in the tekton-operator chart. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
    This test failed immediately, seems unrelated to this change.
    ```
    /bin/sh: 1: set: Illegal option -o pipefail
    make: *** [Makefile:156: test-unit] Error 2
    ```
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by jkandasa** [comment]
@davidumea thanks for the PR. Can you please sign `EasyCLA`?

**Review by jkandasa — APPROVED** [review]
cc @vdemeester @piyush-garg

**Comment by PuneetPunamiya** [comment]
LGTM

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
