### PR TITLE
enable-deep-inspection field to  support both string and bool

### PR DESCRIPTION
**Pull request by rupalibehera**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by rupalibehera** [comment]
@PuneetPunamiya could you please take a look at this ?

**Comment by PuneetPunamiya** [comment]
@rupalibehera did you check the upgrade ?
Is upgrade working fine for operator ?

**Comment by rupalibehera** [comment]
upgrade is working fine, I tested with this PR https://github.com/tektoncd/operator/pull/2179 and on kind, I think so we can merge this one

**Comment by rupalibehera** [comment]
closing this PR on behalf of https://github.com/tektoncd/operator/pull/2179

**Pull request closed without merging**
