### PR TITLE
Add Metrics for TektonResult

### PR DESCRIPTION
**Pull request by khrm**
Added Metrics `results_reconciled` which tells us what type of logging is being used for results installation.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Metrics `results_reconciled` added which has `log_type` which tells us logging type used during installtion of results.
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind feature

**Review by jkandasa — COMMENTED** [review]
@khrm can you please resolve the followings?
* I see two commits and one is related to tektonChains. I see you have another PR about chains #1598 
* In this PR, I see some of the changes not related to metrics. Can you please elaborate more about those changes in the PR description. or create a separate PR for that.

**Comment by piyush-garg** [comment]
@kbaig you need to rebase this as the chains one is approved now

**Comment by khrm** [comment]
Sure. Rebasing this.

**Comment by vdemeester** [comment]
Seems like it needs a rebase.

**Comment by khrm** [comment]
@vdemeester Now, it doesn't needs rebase.

**Comment by jkandasa** [comment]
@khrm can you please add unit test to `metrics.go`

**Comment by piyush-garg** [comment]
lgtm cc @jkandasa

**Review by khrm — COMMENTED** [review]
@jkandasa 
I have added the unit tests for metrics.

**Pull request merged**
