### PR TITLE
[OpenShift] Add a version label on namespace

### PR DESCRIPTION
**Pull request by sm43**
This adds a version label to namespace which would be useful while
upgrading for rbac resources.

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
