### PR TITLE
Add the packages into the dependencies to generate knative/pkg based code

### PR DESCRIPTION
**Pull request by houshengbo**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
i see, this pr is all the dependencies to support patch #119  and #120

**Comment by nikhil-thomas** [comment]
@houshengbo if i understand correctly, you have created #118 (this pr) and #119 to make it easy for us to review the changes in parts.

commits in #118 and #119 are in the history of #120
commit history: https://pastebin.com/F1dgn7S7

so if we all agree on these patches, we have to only merge #120

cc @vdemeester @sthaha @piyush-garg @vincent-pli

**Comment by houshengbo** [comment]
@nikhil-thomas correct .
119 includes 118 as well. 119 depends on 118. 120 depends on 119.

**Comment by nikhil-thomas** [comment]
@houshengbo as the critical commits form this patch got merged through https://github.com/tektoncd/operator/pull/121, shall we close https://github.com/tektoncd/operator/pull/120, https://github.com/tektoncd/operator/pull/119, and https://github.com/tektoncd/operator/pull/118 

cc @vdemeester

**Pull request closed without merging**
