### PR TITLE
Fix postgres:13 sha256 image with multi-arched image

### LINKED ISSUE #1114: Testcases missing multi-arched images
Recently added test cases uses images which are not multi-arched. e.g. `postgres13` images in [db.yaml](https://github.com/tektoncd/operator/blob/1d1d5f246534cf551d265631d9e87aae665b7f2d/test/e2e/common/testdata/db.yaml#L72 ) and [update-db-deployment.yaml](https://github.com/tektoncd/operator/blob/e51abf490dd3b636ee7947abaaee9489dc2a68ee/pkg/reconciler/openshift/tektonhub/testdata/update-db-deployment.yaml#L33).
The Operator CI job on dogfooding cluster fails for P/Z when multi-arched images are not used. e.g. [tekton-operator-ppc64le-nightly-run-4ccfr](https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-p/pipelineruns/tekton-operator-ppc64le-nightly-run-4ccfr?pipelineTask=e2e-test-operator&step=run-e2e-tests&retry=0) and [tekton-operator-s390x-nightly-run-x6nwh](https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-z/pipelineruns/tekton-operator-s390x-nightly-run-x6nwh?pipelineTask=e2e-test-operator&step=run-e2e-tests&retry=0).

```
Finished run, return code is 0
XML report written to /tmp/tmp.biaUBzpey0/junit_i8rTAjte.xml
Test log written to /tmp/tmp.biaUBzpey0/go_test_i8rTAjte.log
***************************************
***         E2E TEST FAILED         ***
***    Start of information dump    ***
***************************************
>>> All resources:
NAMESPACE         NAME                                                 READY   STATUS             RESTARTS        AGE
db                pod/tekton-hub-db-75c4f48b7b-fdvks                   0/1     CrashLoopBackOff   13 (2m6s ago)   44m
default           pod/nfs-client-provisioner-7df86c59f8-b224w          1/1     Running            0               86m
kube-flannel      pod/kube-flannel-ds-fldfp                            1/1     Running            0               86m
kube-flannel      pod/kube-flannel-ds-vqvft                            1/1     Running            0               86m
kube-system       pod/coredns-78fcd69978-lctw2                         1/1     Running            0               86m
kube-system       pod/coredns-78fcd69978-tvs26                         1/1     Running            0               86m
kube-system       pod/etcd-tekton-ci-zmaster-node                      1/1     Running            0               86m
kube-system       pod/kube-apiserver-tekton-ci-zmaster-node            1/1     Running            0               86m
kube-system       pod/kube-controller-manager-tekton-ci-zmaster-node   1/1     Running            0               86m
```

Currently, we have raised a [PR#1111](https://github.com/tektoncd/operator/pull/1111), to fix this.
**We are raising this issue, to always include multi-arched images when a new test case is added.**

### PR DESCRIPTION
**Pull request by kabhiibm**
# Changes

The CI Tekton/Operator builds are failing due to Postgres db container:-
https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-p/pipelineruns/tekton-operator-ppc64le-nightly-run-4ccfr?pipelineTask=e2e-test-operator&step=run-e2e-tests&retry=0

```
Finished run, return code is 0
XML report written to /tmp/tmp.biaUBzpey0/junit_i8rTAjte.xml
Test log written to /tmp/tmp.biaUBzpey0/go_test_i8rTAjte.log
***************************************
***         E2E TEST FAILED         ***
***    Start of information dump    ***
***************************************
>>> All resources:
NAMESPACE         NAME                                                 READY   STATUS             RESTARTS        AGE
db                pod/tekton-hub-db-75c4f48b7b-fdvks                   0/1     CrashLoopBackOff   13 (2m6s ago)   44m
default           pod/nfs-client-provisioner-7df86c59f8-b224w          1/1     Running            0               86m
kube-flannel      pod/kube-flannel-ds-fldfp                            1/1     Running            0               86m
kube-flannel      pod/kube-flannel-ds-vqvft                            1/1     Running            0               86m
kube-system       pod/coredns-78fcd69978-lctw2                         1/1     Running            0               86m
kube-system       pod/coredns-78fcd69978-tvs26                         1/1     Running            0               86m
kube-system       pod/etcd-tekton-ci-zmaster-node                      1/1     Running            0               86m
kube-system       pod/kube-apiserver-tekton-ci-zmaster-node            1/1     Running            0               86m
kube-system       pod/kube-controller-manager-tekton-ci-zmaster-node   1/1     Running            0               86m
```

From investigation we found the postgres 13 image used sha256 value that is not multi-arched. Postgres multi-arched image can be used by removing the sha256 part for the YAML file.

Fixes #1114

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Fix postgres:13 sha256 image with multi-arched image in e2e tests
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by Basavaraju-G** [comment]
@pradeepitm12 @piyush-garg would you please check this PR?

**Pull request merged**
