### PR TITLE
Add dependencies under vendor 🧗‍♂️

### PR DESCRIPTION
**Pull request by houshengbo**
# Changes

Fixes: #17 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by houshengbo** [comment]
does operator-sdk require certain permission to the dependencies under vendor? 
why is there error after just adding the dependencies?

**Comment by nikhil-thomas** [comment]
@sthaha

**Comment by vdemeester** [comment]
/hold
I'm not a huge fan of this `mv` thingy.. we should understand why it fails

**Comment by houshengbo** [comment]
I regenerate the vendor with the go version 1.11.4, equivalent to the one in prow job. All the issues I had before have gone. 
It seems to me that higher version of go like 1.12.9 generates the vendor/modules.txt for 1.11.x, but still quite makes the backward-compatibility.

**Comment by houshengbo** [comment]
@vdemeester We can unhold it now.

**Comment by nikhil-thomas** [comment]
@houshengbo 
this looks good.
could your rebase and add a Make target for `go mod tidy` and mention that in Readme

**Pull request merged**
