### PR TITLE
Add Install and Upragde metrics for Pipeline and Triggers

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
PR address displaying of metrics when Pipeline and Triggers Install/Upgrade

PR incorporates changes from @khrm PR https://github.com/tektoncd/operator/pull/334 and @sm43 PR https://github.com/sm43/tektoncd-operator/tree/metrics

/cc @vdemeester @nikhil-thomas @sm43 @khrm

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Operator exposes metrics to display Installation and Upgradation count for Tekton Pipeline and Triggers
```

#### Pipeline Install and Upgrade count
pipeline1

#### Triggers Install and Upgrade count
triggers1

### CODE REVIEW

**Comment by savitaashture** [comment]
@nikhil-thomas @sm43 addressed all the review comment provided in this PR https://github.com/tektoncd/operator/pull/443 

And its ready for another review 
PTAL

**Comment by sm43** [comment]
we can also add the new configmap for validation in webhook
https://github.com/tektoncd/operator/blob/0870789296e0f3212d5ca75a68cf3afac24ad0a7/pkg/webhook/webhook.go#L91
https://github.com/tektoncd/operator/blob/0870789296e0f3212d5ca75a68cf3afac24ad0a7/pkg/webhook/webhook.go#L101

**Comment by nikhil-thomas** [comment]
> /lgtm /hold @nikhil-thomas to take a look ! :)

Thanks 🧑‍💻

**Pull request merged**
