### PR TITLE
Update triggers to use v1beta1 and bump triggers, pipeline, knative and k8s version

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
* Updated triggers code to use `v1beta1` 
* Bump pipeline, triggers, knative and k8s version

```
K8S_VERSION="v0.21.4"
TRIGGERS_VERSION="v0.16.0"
PIPELINE_VERSION="v0.27.3"
knative.dev/pkg v0.0.0-20210827184538-2bd91f75571c
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Updated triggers to use v1beta1 apis
```

### CODE REVIEW

**Review by vdemeester — CHANGES_REQUESTED** [review]
I wonder why `.bin` files have been added, they should be in the `.gitignore` 🤔

**Comment by savitaashture** [comment]
> I wonder why `.bin` files have been added, they should be in the `.gitignore`

that's added mistakenly while doing PR  :laughing:

**Comment by sm43** [comment]
https://github.com/tektoncd/operator/blob/a1a0d67dc058dbe3dab9343a3b9c058d28a770ad/pkg/reconciler/openshift/annotation/annotation.go#L145
do we need to update the version here?

**Comment by savitaashture** [comment]
> https://github.com/tektoncd/operator/blob/a1a0d67dc058dbe3dab9343a3b9c058d28a770ad/pkg/reconciler/openshift/annotation/annotation.go#L145
> 
> 
> do we need to update the version here?

Yes updated here https://github.com/tektoncd/operator/pull/388/files?file-filters%5B%5D=.go&hide-deleted-files=true#diff-b1cec14612915fa7e56c474b9dc04e14e1e246ec7ad9abd7390d2ad44cb36eadR145

**Pull request merged**
