### PR TITLE
Access to Results Service and Route for system:authenticated user

### PR DESCRIPTION
**Pull request by khrm**
# Changes
Enable Access to Results Service and Route for system:authenticated user so that enduser knows where to make the call.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/assign @jkandasa @vdemeester 
/kind feature

**Review by khrm — COMMENTED** [review]
/test pull-tekton-operator-go-coverage

**Comment by khrm** [comment]
This shouldn't require rebase but tide is asking for it. Is there some misconfiguration?

**Comment by piyush-garg** [comment]
/lgtm
if we want to make results accessible to all

**Review by khrm — COMMENTED** [review]
/assign @vdemeester @jkandasa  @concaf Can we get this approved?

**Review by jkandasa — APPROVED** [review]

**Pull request merged**
