### PR TITLE
Updates Hub docs based on the new changes of Hub v1.8.0

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
Signed-off-by: Puneet Punamiya ppunamiy@redhat.com

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @concaf @sm43 @piyush-garg

**Comment by piyush-garg** [comment]
@PuneetPunamiya
1. Do we still need the config update part with the login setup?
2. Can you please add/update docs for catalog refresh also?
3. Can you please remove the docs for the initial resource population step if we don't require them anymore?

**Pull request merged**
