### PR TITLE
Removed Newline in Buildah Results

### PR DESCRIPTION
**Pull request by Aneesh-M-Bhat**
# Changes

https://issues.redhat.com/browse/SRVKP-3160
Basically according to this issue, there was a newline occuring in the results of buildah task.
Changed here as follows -> https://github.com/tektoncd/catalog/commit/5f899c0d5466022da3d49ea20d503d75e66e8c5b

Did the same in the buildah present in the operator.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Comment by khrm** [comment]
@Aneesh-M-Bhat Please sign the cla.

**Comment by savitaashture** [comment]
Hi @Aneesh-M-Bhat Can you sign the CLA ?

**Comment by Aneesh-M-Bhat** [comment]
done with the CLA, sorry for the delay.

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
