### PR TITLE
Use ./hack/feth-releases.sh for the release task…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

We have an existing script that does fetch the release. Not using it
in the release tasks is proving to be very error prone as the script
might differ between the too, and thus we end up with broken
releases (missing files, …)

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Fix fetch-components tasks in order to fix missing files in releases.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
I'll have to backport those on the different release branches too 👼🏼

**Comment by nikhil-thomas** [comment]
closes https://github.com/tektoncd/operator/issues/465

**Pull request merged**
