### PR TITLE
Add Triggers v0.2.1 release as addon

### PR DESCRIPTION
**Pull request by khrm**
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Triggers v0.2.1 added as addon
```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@khrm thank you for this patch

do we need to keep addon trigger 0.2.0. Could we remove it and provide only 0.2.1.

https://github.com/tektoncd/operator/tree/master/deploy/resources/addons/trigger/v0.2.0

**Comment by khrm** [comment]
@nikhil-thomas  Yes. Removing it.

**Pull request merged**
