### PR TITLE
add jkhelil to owners file

### PR DESCRIPTION
**Pull request by jkhelil**
# Changes
Add jkhelil to Owners file

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by jkhelil** [comment]
hey @jkandasa, can you have a look please.
Thank you

**Comment by jkandasa** [comment]
@jkhelil thanks for the PR
AFAIK, we can not add a user into `approver` and/or `reviewer` list immediately.
users has to be satisfied the requirements from https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md

cc @tektoncd/operator-maintainers

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Comment by khrm** [comment]
You  need to satisfy conditions given here: https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#reviewer

You can see your status at the dashboard here:
https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=review_comments&var-repogroup_name=tektoncd%2Foperator&var-country_name=All

**Comment by khrm** [comment]
/hold
@vdemeester I think @jkhelil doesn't satisy the owner condition. That's why it was on hold.

**Pull request merged**
