### PR TITLE
Add proxy-webhook to the list of built images

### LINKED ISSUE #344: Operator Nightly failing
# Expected Behavior

Operator nightly should pass

# Actual Behavior

It has been failing the last 2 days. On both days, the failure is on the publish-images task.

```
 koparse --path /workspace/output/v20210701-e09614c741/release.yaml --base gcr.io/tekton-nightly/github.com/tektoncd/operator --images gcr.io/tekton-nightly/github.com/tektoncd/operator/cmd/kubernetes/operator:v20210701-e09614c741 gcr.io/tekton-nightly/github.com/tektoncd/operator/cmd/kubernetes/webhook:v20210701-e09614c741
Expected images did not match: Images ['gcr.io/tekton-nightly/github.com/tektoncd/operator/cmd/kubernetes/proxy-webhook:v20210701-e09614c741'] were present but not expected.
apiVersion: v1
```

It seems like a new image `proxy-webhook` was added but the release pipeline was not updated.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Nightly pipeline was failing since a new proxy-webhook binary was added (#330)
Fixes #344

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Review by pradeepitm12 — APPROVED** [review]
/lgtm

**Pull request merged**
