### PR TITLE
Add Results extension manifest to TektonAddon

### LINKED ISSUE #1729: TektonResult Route isn't accessible to OpenShift to system:authenticated user
# Expected Behavior
TektonResult API server Route isn't in OpenShift to system:authenticated user

# Actual Behavior
TektonResult Route isn't in OpenShift to system:authenticated user

```
 ❯ oc get route tekton-results-api-service  -n openshift-pipelines
Error from server (Forbidden): routes.route.openshift.io "tekton-results-api-service" is forbidden: User "developer" cannot get resource "routes" in API group "route.openshift.io" in the namespace "openshift-pipelines"
```

### PR DESCRIPTION
**Pull request by khrm**
# Changes

Fixes #1729

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by concaf** [comment]
needs to be closed

**Review by khrm — COMMENTED** [review]
/close

**Pull request closed without merging**
