### PR TITLE
Upgrade "manifestival"

### PR DESCRIPTION
**Pull request by vincent-pli**
# Changes

The bug https://github.com/manifestival/manifestival/issues/61
has been merged, we need adopt the fix.

fix issue: #105 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@vincent-pli Thank you for this fix :heart: :+1: 

In the future could you make the pr from a branch on you fork, instead of using https://github.com/tektoncd/operator/tree/master-real

**Comment by vincent-pli** [comment]
@nikhil-thomas 
OOOh, sorry for that, my mistake, I will close this one and make another one instead, sorry again.

**Pull request closed without merging**
