### PR TITLE
[openshift] add maven clustertask

### PR DESCRIPTION
**Pull request by pradeepitm12**
This adds maven clustertask using maven image from the internal registry
and removes it from the community tasks

Signed-off-by: Pradeep Kumar <pradkuma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

<i>This is openshift specific change. </i>
With this PR we remove fetching maven task from community task url's which mostly use gcr based images.
Now we have maven clustertask in our addon/clustertasks folder.
This clustertask uses `image-registry.openshift-image-registry.svc:5000/openshift/openjdk-11-rhel8:1.0` image for maven goals from our internal image registry.

### CODE REVIEW

**Comment by pradeepitm12** [comment]
cc: @nikhil-thomas @savitaashture

**Comment by nikhil-thomas** [comment]
pr looks good to me. 
But if we are moving task to operator registry, we have to think about our strategy to create `versioned-tasks` (a duplicate of the task with version in its name.)

we can think about keeping non-versioned Task like this maven task in the kodata and add some logic in operator to create the duplicate versioned tasks.  we will have to add some logic here: https://github.com/tektoncd/operator/blob/e7b2e98e1993bf7522381ab160bbed43a1f4367a/pkg/reconciler/openshift/tektonaddon/tektonaddon.go#L501

we don't have to do this with this pr. @pradeepitm12 could you create a github issue (or jira issue) to capture this.

@piyush-garg

**Comment by nikhil-thomas** [comment]
@pradeepitm12 could you add a release note to the pr description.

**Comment by nikhil-thomas** [comment]
✅ lgtm

**Comment by pradeepitm12** [comment]
> @pradeepitm12 could you add a release note to the pr description.

Please take a look and let me know if we can add something more to it.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
