### PR TITLE
add docs for read-only mode

### PR DESCRIPTION
**Pull request by charlesmorin**
# Changes

Adds documentation about the read-only mode. More precisely, it will describe the features that are enabled when turning off `readonly` mode.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by charlesmorin** [comment]
Looking at https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md#does-my-pull-request-need-a-release-note

I am not clear whether I need a release note or not. I tend to think it's not required given it's not impacting the actual source code.

**Review by jkandasa — APPROVED** [review]
/lgtm

**Pull request merged**
