### PR TITLE
Add script for release branch creation

### PR DESCRIPTION
**Pull request by nikhil-thomas**
This script will:

- guide a release manager through picking latest releases of components
- set versions labels
- pull OpenShift addon tasks
- outputs a list of commands for running release pipeline and publishing release
    - eg: [output-log](https://gist.github.com/nikhil-thomas/96c0e52cc3819b1a77096d21f57940e8)

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@vdemeester

**Comment by nikhil-thomas** [comment]
@vdemeester i have updated this with latest "workpace based release-draft pipeline" .
shall we merge this

**Review by vdemeester — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
/lgtm

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Review by vdemeester — COMMENTED** [review]
/retest
/lgtm

**Comment by nikhil-thomas** [comment]
as https://github.com/tektoncd/operator/pull/769 has merged, ci should pass

**Pull request merged**
