### PR TITLE
Switch to ko command to build the image

### PR DESCRIPTION
**Pull request by houshengbo**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by sthaha** [comment]
@houshengbo thank for a the PR. 

image
I am a bit scared to click on the "Files" :D . My browser would melt down :D

**Comment by sthaha** [comment]
cc: @nikhil-thomas

**Comment by nikhil-thomas** [comment]
https://github.com/tektoncd/operator/pull/118#issuecomment-659245397

**Comment by nikhil-thomas** [comment]
@houshengbo could you add a brief doc on how to run tests while development.
The tests are breaking for me. I am lost trying to track down what is missing.

**Comment by vdemeester** [comment]
I think so yes :upside_down_face:

**Pull request closed without merging**
