### PR TITLE
Update version and yaml file for triggers and pipeline to 0.14.1 and 0.24.1

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
* Updated version of Triggers and Pipeline to 0.14.1 and 0.24.1 respectively
* Add release yamls for Triggers and Pipeline to 0.14.1 and 0.24.1 respectively

/cc @vdemeester @nikhil-thomas 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Bump dependency for Triggers and Pipeline to 0.14.1 and 0.24.1
```

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
@savitaashture is it necesary to update `tektncd/triggers` vendor dependency while updatinf payload for kubernetes.

**Comment by savitaashture** [comment]
> @savitaashture is it necesary to update `tektncd/triggers` vendor dependency while updatinf payload for kubernetes.

Actually on Openshift platform when enable this label https://github.com/tektoncd/operator/blob/main/pkg/reconciler/openshift/annotation/annotation.go#L169 and create any trigger example its giving below error

```
clusterrolebinding.rbac.authorization.k8s.io/tekton-triggers-example-clusterbinding created
secret/github-secret created
Error from server (BadRequest): error when creating "examples/github/github-eventlistener-interceptor.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "ref"
```

may be its because  of old vendor code so updated that and i see no errors

**Comment by nikhil-thomas** [comment]
/lgtm 🧑‍💻 👍 
merging this so that we can make a operatorHub release. 🙂

**Pull request merged**
