### PR TITLE
Fix chains label for e2e tests based on new version

### PR DESCRIPTION
**Pull request by piyush-garg**
This will fix the chains e2e tests for new releases of chains
as the labels have been updated there

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Fix chains label for e2e tests based on new version
```

### CODE REVIEW

**Review by concaf — APPROVED** [review]
/lgtm

**Review by rupalibehera — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
