### PR TITLE
Remove occurences of podsecuritypolicies in code

### PR DESCRIPTION
**Pull request by piyush-garg**
This will remove occurence of podsecuritypolicies in code
roles and permissions, csv data, crd data etc

Also remove the filtering we do for psp and hpa
as that is not valid anymore

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Remove occurences of podsecuritypolicies in code
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
i see we do some filtering on psp and hpa in manifest, we should not doing that too. will remove them

**Comment by piyush-garg** [comment]
/hold cancel
cc @vdemeester @jkandasa

**Comment by jkandasa** [comment]
@piyush-garg  I see the word `podsecuritypolicies` in different files than you have updated here. Is that expected?

```
$ grep -irn "podsecuritypolicie" . --exclude-dir=vendor
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:115:  resources: ["podsecuritypolicies"]
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:179:  resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
./pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml:76:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/transformers_test.go:396:			t.Errorf("Replace 'tekton-pipelines' in the wrong rule (podsecuritypolicies)")
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:115:  resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:179:  resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-role.yaml:9:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/04-operand-label-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/03-with-skipchecks-test-expected-result.yaml:57:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/02-no-predicates-test-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/01-sample-tektoncd-pipelines-release.yaml:55:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
./operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml:158:      - kind: podsecuritypolicies
./operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml:644:          - podsecuritypolicies
./operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml:201:      - kind: podsecuritypolicies
./operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml:594:          - podsecuritypolicies
./config/openshift/base/role.yaml:200:  - podsecuritypolicies
./config/base/role.yaml:199:  - podsecuritypolicies
./chart/templates/rbac.yaml:217:  - podsecuritypolicies
./chart/templates/rbac.yaml:571:    - podsecuritypolicies
./chart/templates/openshift-crds.yaml:509:      - podsecuritypolicies
```

**Comment by piyush-garg** [comment]
> @piyush-garg I see the word `podsecuritypolicies` in different files than you have updated here. Is that expected?
> 
> ```
> $ grep -irn "podsecuritypolicie" . --exclude-dir=vendor
> ./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:115:  resources: ["podsecuritypolicies"]
> ./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:179:  resources: ["podsecuritypolicies"]
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml:76:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/transformers_test.go:396:			t.Errorf("Replace 'tekton-pipelines' in the wrong rule (podsecuritypolicies)")
> ./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:115:  resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:179:  resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-role.yaml:9:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/04-operand-label-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/03-with-skipchecks-test-expected-result.yaml:57:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/02-no-predicates-test-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/01-sample-tektoncd-pipelines-release.yaml:55:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
> ./operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml:158:      - kind: podsecuritypolicies
> ./operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml:644:          - podsecuritypolicies
> ./operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml:201:      - kind: podsecuritypolicies
> ./operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml:594:          - podsecuritypolicies
> ./config/openshift/base/role.yaml:200:  - podsecuritypolicies
> ./config/base/role.yaml:199:  - podsecuritypolicies
> ./chart/templates/rbac.yaml:217:  - podsecuritypolicies
> ./chart/templates/rbac.yaml:571:    - podsecuritypolicies
> ./chart/templates/openshift-crds.yaml:509:      - podsecuritypolicies
> ```

These are the remaining ones after my PR ?

**Comment by jkandasa** [comment]
> These are the remaining ones after my PR ?

@piyush-garg No, that one from main branch

Here are the remaining ones from your branch
```
$ git clone https://github.com/piyush-garg/operator.git
Cloning into 'operator'...
remote: Enumerating objects: 50252, done.
remote: Counting objects: 100% (1225/1225), done.
remote: Compressing objects: 100% (868/868), done.
remote: Total 50252 (delta 274), reused 1131 (delta 236), pack-reused 49027
Receiving objects: 100% (50252/50252), 79.49 MiB | 1.50 MiB/s, done.
Resolving deltas: 100% (25657/25657), done.

$ cd operator/
$ git checkout rem_psp
branch 'rem_psp' set up to track 'origin/rem_psp'.
Switched to a new branch 'rem_psp'

$ grep -irn "podsecuritypolicie" . --exclude-dir=vendor
./operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml:594:          - podsecuritypolicies
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:115:  resources: ["podsecuritypolicies"]
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:179:  resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
./pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml:76:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/transformers_test.go:396:			t.Errorf("Replace 'tekton-pipelines' in the wrong rule (podsecuritypolicies)")
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:115:  resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:179:  resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-role.yaml:9:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/04-operand-label-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/03-with-skipchecks-test-expected-result.yaml:57:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/02-no-predicates-test-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/01-sample-tektoncd-pipelines-release.yaml:55:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
```

**Comment by jkandasa** [comment]
updated list with the word `podsecuritypolic` (earlier it was `podsecuritypolicie`)

```
$ grep -irn "podsecuritypolic" . --exclude-dir=vendor
./operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml:594:          - podsecuritypolicies
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:39:kind: PodSecurityPolicy
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:115:  resources: ["podsecuritypolicies"]
./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:179:  resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:39:kind: PodSecurityPolicy
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
./pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml:76:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/transformers_test.go:393:	podsecuritypolicyRule := rules[0].(map[string]interface{})
./pkg/reconciler/common/transformers_test.go:394:	for _, name := range podsecuritypolicyRule["resourceNames"].([]interface{}) {
./pkg/reconciler/common/transformers_test.go:396:			t.Errorf("Replace 'tekton-pipelines' in the wrong rule (podsecuritypolicies)")
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:39:kind: PodSecurityPolicy
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:115:  resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:179:  resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-role.yaml:9:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/04-operand-label-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/03-with-skipchecks-test-expected-result.yaml:57:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/02-no-predicates-test-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/testdata/inject-label/01-sample-tektoncd-pipelines-release.yaml:55:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:39:kind: PodSecurityPolicy
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
```

**Comment by piyush-garg** [comment]
@jkandasa all the occurrences have been fixed.

**Comment by piyush-garg** [comment]
> updated list with the word `podsecuritypolic` (earlier it was `podsecuritypolicie`)
> 
> ```
> $ grep -irn "podsecuritypolic" . --exclude-dir=vendor
> ./operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml:594:          - podsecuritypolicies
> ./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:39:kind: PodSecurityPolicy
> ./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:115:  resources: ["podsecuritypolicies"]
> ./test/manifests/tekton-pipeline/0.15.2/release.notags.yaml:179:  resources: ["podsecuritypolicies"]
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:39:kind: PodSecurityPolicy
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/shared/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml:76:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/transformers_test.go:393:	podsecuritypolicyRule := rules[0].(map[string]interface{})
> ./pkg/reconciler/common/transformers_test.go:394:	for _, name := range podsecuritypolicyRule["resourceNames"].([]interface{}) {
> ./pkg/reconciler/common/transformers_test.go:396:			t.Errorf("Replace 'tekton-pipelines' in the wrong rule (podsecuritypolicies)")
> ./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:39:kind: PodSecurityPolicy
> ./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:115:  resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml:179:  resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-role.yaml:9:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/04-operand-label-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/03-with-skipchecks-test-expected-result.yaml:57:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/02-no-predicates-test-expected-result.yaml:58:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/testdata/inject-label/01-sample-tektoncd-pipelines-release.yaml:55:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:39:kind: PodSecurityPolicy
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:203:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:253:    resources: ["podsecuritypolicies"]
> ./pkg/reconciler/common/tektoninstallerset/testdata/release.yaml:286:    resources: ["podsecuritypolicies"]
> ```

@jkandasa All the occurrences have been fixed

**Review by jkandasa — APPROVED** [review]
LGTM

**Comment by piyush-garg** [comment]
> /lgtm Do we want to backport this in 0.65.x ?

i think we should do that

**Comment by piyush-garg** [comment]
cherry-pick release-v0.65.x

**Pull request merged**
