### PR TITLE
cosign dependency bump

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

- go.mod: switch to go 1.18
- Update cosign dependency to latest : this fixes a bunch of security issues

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Update cosign to v1.11.0
```

### CODE REVIEW

**Comment by afrittoli** [comment]
```
--- FAIL: TestTektonChainsGettingStartedTutorial (92.87s)
    --- PASS: TestTektonChainsGettingStartedTutorial/create-pipeline (20.03s)
    --- PASS: TestTektonChainsGettingStartedTutorial/create-chain (10.03s)
    --- PASS: TestTektonChainsGettingStartedTutorial/create_cosign_key_pair (1.65s)
    --- PASS: TestTektonChainsGettingStartedTutorial/replace_Chains_ConfigMap (0.10s)
    --- PASS: TestTektonChainsGettingStartedTutorial/restart_chains_pod (0.10s)
    --- PASS: TestTektonChainsGettingStartedTutorial/create_TaskRun (0.18s)
    --- PASS: TestTektonChainsGettingStartedTutorial/wait_for_TaskRun_to_succeed (20.04s)
    --- PASS: TestTektonChainsGettingStartedTutorial/wait_for_TaskRun_to_get_signed (0.01s)
    --- FAIL: TestTektonChainsGettingStartedTutorial/cosign_verify-blob (0.01s)
```

I guess the failure is an actual one here?

**Comment by afrittoli** [comment]
https://github.com/tektoncd/operator/blob/ed48f3dfbf6394c936cdbbeee00ecdde173f9630/test/e2e/common/04_tektonchainsgettingstartedtutorial_test.go#L212

**Comment by piyush-garg** [comment]
@vdemeester cosign has been bumped, can you rebase the PR if there are any other changes or close if no other changes?

**Comment by vdemeester** [comment]
I'll close for now..

**Pull request closed without merging**
