### PR TITLE
Revert "Fix Conflict between Results PreReconciler and Reconciler"

### LINKED ISSUE #2042: Revert Results Prereconcile and reconcile resolution PR
This PR isn't needed for the next release. It was just needed for 1.15

### PR DESCRIPTION
**Pull request by khrm**
This reverts commit c1f9bfcb66f23fe580903760fc425d11898894b8. #2008

Fixes #2042 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/assign @jkandasa

**Review by jkandasa — APPROVED** [review]
/lgtm

**Pull request merged**
