### PR TITLE
Update pipeline to 0.41.0…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This also update the go.mod to 1.18

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Comment by vdemeester** [comment]
oh I forgot to re-run the generate code..

**Comment by vdemeester** [comment]
oh I forgot to re-run the generate code..

**Pull request merged**
