### PR TITLE
[release-v0.64.x] fix build test failures, happens after plumbing pr-1369

### PR DESCRIPTION
**Pull request by jkandasa**
# Changes
* same as https://github.com/tektoncd/operator/pull/1345 
* but only few changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by chmouel** [comment]
is the build failure linters errors?

otherwise lgtm!

**Comment by jkandasa** [comment]
@chmouel Thanks for the review comments! Yes, this PR fixes build failure linter errors.
recently build environment moved to go1.19+ and reports these changes.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
