### PR TITLE
Adds params to customize TektonAddon component on OpenShift

### PR DESCRIPTION
**Pull request by sm43**
- This adds params in TektonConfig which would be copied to Tekton Addon
CR to customize installation of different components of Addons.
- If the params are not passed in TektonConfig CR, controller will add them
with default values.
- User can change values in TektonConfig to change the component installation
of Addon.
- If Addon is created through TektonConfig CR, and if later values are changed in
Addon CR, it will get overwritten by TektonConfig CR values.

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

**TektonConfig CR**
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  targetNamespace: openshift-pipelines
  addon:
    params:
    - name: clusterTasks
      value: "true"
    - name: pipelineTemplates
      value: "true"

```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
User can customize installation of TektonAddon Component by passing params in TektonConfig CR if addon is created through it
or directly in TektonAddon.

If params are not passed, controller will add params with default values.

Addons params:

- `clusterTask` (Default: true) Installs ClusterTask
- `pipelinesTemplates` (Default: true) Installs PipelinesTemplates

*This is only for OpenShift Platform
```

### CODE REVIEW

**Comment by sm43** [comment]
/cc @nikhil-thomas @vdemeester @savitaashture 
Tests are yet to be added. but can be reviewed :D
/hold

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Comment by savitaashture** [comment]
@sm43 could you rebase ?

/hold

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Review by savitaashture — APPROVED** [review]
/lgtm

**Pull request merged**
