### PR TITLE
Skip Tekton Chain tests for Z and Power platforms

### PR DESCRIPTION
**Pull request by manojbison**
# Changes

At this moment Tekton Chains is available only for Intel platform, so the tests on Z and Power platforms should be skipped.

The issue to discuss multi-arch options for Tekton Chains is open https://github.com/tektoncd/chains/issues/459

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

```release-note
NONE
```
-->

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by piyush-garg** [comment]
@manojbison Can you please squash the commits?

**Comment by manojbison** [comment]
@piyush-garg can you please review this PR?

**Comment by piyush-garg** [comment]
> @piyush-garg can you please review this PR Now ?

PR looks good, you need to squash the commits

**Comment by manojbison** [comment]
> @manojbison One thing, is this env already getting set somewhere, or have you tested this?

Yes, we tested locally and this variable is set in task env : 
env:
  - name: PLATFORM
    value: linux/$(params.target-arch)

**Comment by piyush-garg** [comment]
> > @manojbison One thing, is this env already getting set somewhere, or have you tested this?
> 
> Yes, we tested locally and this variable is set in task env :
> 
> https://github.com/tektoncd/plumbing/blob/9e41ff8fc888630dd6eb36d2486dbb5e0caa3b66/tekton/resources/nightly-tests/operator-deploy-test-s390x-template.yaml#L119
> 
> env:
> 
> * name: PLATFORM
>   value: linux/$(params.target-arch)

Aah ohk, this will work on CI then but for local development, it will still be the issue.

**Comment by piyush-garg** [comment]
We can do it as a follow-up for local development if anything required

/lgtm

**Pull request merged**
