### PR TITLE
Move clustertask and clustertriggerbinding role to component

### PR DESCRIPTION
**Pull request by piyush-garg**
This will move clustertask and clustertriggerbinding view permissions for all system authenticated users on openshift to be installed along with component installation instead of doing it with addon resources.

This will help users to move to basic or lite profile without permission issues, also if user disable default clustertasks installation then also permission issue will not happen

Also clustertask permissions were getting created as part of all installersets like custom and versioned installerset, and later in new versioned installerset also if upgraded. This was creating race between the different installerset reconiler to update resource because of the different installerset name was getting added to ownerReference resulting in different yaml and sha value, so this will also fix that as we moved the permissions out of addon installerset and there will be single instance. I have changed the name of resources to not conflict with old name and we can users to delete old clustertask installerset if they are not using old clustertasks

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Move clustertask and clustertriggerbinding role to component
```

### CODE REVIEW

**Comment by savitaashture** [comment]
Should we do this for https://github.com/tektoncd/operator/tree/main/cmd/openshift/operator/kodata/tekton-addon/addons/07-ecosystem ?

**Review by jkandasa — APPROVED** [review]
LGTM

**Comment by piyush-garg** [comment]
> Should we do this for https://github.com/tektoncd/operator/tree/main/cmd/openshift/operator/kodata/tekton-addon/addons/07-ecosystem ?

these roles are specific to getting task only in openshift-pipelines, while the clustertask and clustertriggerbinding are different case as these are clustertwide resources and end up in breaking profiles, UI etc

> 
> > I have changed the name of resources to not conflict with old name and we can users to delete old clustertask installerset if they are not using old clustertasks
> 
> Should we indicate this in RN ? and is this a breaking change for existing users ?

changing the name of the role/rolebinding which is not exposed to user, should not be a breaking change for users

**Comment by PuneetPunamiya** [comment]
Great findings 🙌🏻
/lgtm

**Pull request merged**
